### ISSUE TITLE
SortableBehavior::move is called twice which results in "chaos"

### ISSUE THREAD

**Issue by markwatney2016** [hacheraw/sortable#1]
Calling `$this->Elements->move($row_id, $new_place);` (e.g. in a Controller) seems to always result in a second call of this `move()` method. The reason for this is that `SortableBehavior::move` will call `$this->_table->save($this->row);` which triggers `SortableBehavior::beforeSave` to be called wich itself will call `$this->move($entity->id, $entity->{$field}, false);`.

This leads to inappropriate order values.

Examle: Moving the last element to position 0 **twice**:

BEFORE
> ![grafik](https://github.com/hacheraw/sortable/assets/22563689/6f8798d7-d144-435d-a916-7e3e4003bc77)

AFTER
> ![grafik](https://github.com/hacheraw/sortable/assets/22563689/5459b1a2-2347-4e61-810d-76f7232fcc3b)

Note: Removing `SortableBehavior::beforeSave` solves the problem but I guess this event listener ist necessary when an entity is edited to make sure that the order is adjusted properly.

**Comment by hacheraw** [comment]
Hello Mark.
I'll se what I can do when I have the time. Thanks for letting me know.

**Comment by roland-w-2024** [comment]
Thanks for the merge @hacheraw 🙂 Do you plan to release a new version of this package so that it can be installed via Composer via `composer update`?

**Comment by hacheraw** [comment]
Released! New version available on packagist.

**Comment by roland-w-2024** [comment]
Thanks a lot! 🚀
